[tool.poetry]
name = "vanquisher"
version = "0.1.0"
description = "Vanquisher is a game about exploration, looting, evolving and honing, and cleansing the evil off the lands of Hillivet. And about shops."
authors = ["Gustavo6046 <rehermann6046@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
typer = "^0.3.2"
uvicorn = {extras = ["standard"], version = "^0.13.3"}
pygame = "^2.0.1"
Js2Py = "^0.70"
anyio = "^2.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
tox = "^3.21.0"
snakeviz = "^2.1.0"
mypy = "^0.790"
flake8 = "^3.8.4"
pylint = "^2.6.0"
rope = "^0.18.0"
plotnine = "^0.7.1"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
