# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]

    name: Unit Testing on Python ${{ matrix.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
        
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v4
        
      - name: Run pytest
        run:  poetry run pytest

  lint:
    runs-on: ubuntu-latest
    
    name: Linting
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
        
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v4
        
        # Linters, in descending order of precedence
      - name: Run mypy
        run:  poetry run mypy vanquisher
        
      - name: Run pylint
        run:  poetry run pylint vanquisher
        
      - name: Run black (check)
        run:  poetry run black -c vanquisher
        
      - name: Run flake8
        run:  poetry run flake8 -c vanquisher
      
      - name: Run isort (check)
        run:  poetry run isort -c vanquisher

  #build-win:
  #  runs-on: ubuntu-latest
  #  
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2
  #      
  #    - name: PyInstaller Windows
  #      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
  #      with:
  #        path: vanquisher
  #
  #    - uses: actions/upload-artifact@v2
  #      with:
  #        name: name-of-artifact
  #        path: dist/windows
